kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dnd-tools
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8000
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30400
        hostPort: 4000
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30434
        hostPort: 11435
        listenAddress: "127.0.0.1"
        protocol: TCP
